### ISSUE TITLE
Failure to run visualqc due (presumably) to mrivis change

### ISSUE THREAD

**Issue by cfhammill** [raamana/visualqc#13]
* visualqa version: 0.3+68.gb01c5de.dirty
* Python version: 3.6.4
* Operating System: Ubuntu 16.04

### Description

Package version mismatch with `mrivis` causes failure to load `mrivis.base`. 

### What I Did

Installed visualqc using setup.py and  attempt to run `visualqc_t1_mri`

```
./visualqc_t1_mri 
/axiom2/projects/software/arch/linux-xenial-xerus/python-modules/20180122/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "./visualqc_t1_mri", line 11, in <module>
    load_entry_point('visualqc==0.3+68.gb01c5de.dirty', 'console_scripts', 'visualqc_t1_mri')()
  File "/axiom2/projects/software/arch/linux-xenial-xerus/python-setuptools/20180327/lib/python3.6/site-packages/setuptools-39.0.1-py3.6.egg/pkg_resources/__init__.py", line 480, in load_entry_point
  File "/axiom2/projects/software/arch/linux-xenial-xerus/python-setuptools/20180327/lib/python3.6/site-packages/setuptools-39.0.1-py3.6.egg/pkg_resources/__init__.py", line 2693, in load_entry_point
  File "/axiom2/projects/software/arch/linux-xenial-xerus/python-setuptools/20180327/lib/python3.6/site-packages/setuptools-39.0.1-py3.6.egg/pkg_resources/__init__.py", line 2324, in load
  File "/axiom2/projects/software/arch/linux-xenial-xerus/python-setuptools/20180327/lib/python3.6/site-packages/setuptools-39.0.1-py3.6.egg/pkg_resources/__init__.py", line 2330, in resolve
  File "/axiom2/projects/software/arch/linux-xenial-xerus/visualqc/0.3/lib/python3.6/site-packages/visualqc-0.3+68.gb01c5de.dirty-py3.6.egg/visualqc/__t1_mri__.py", line 4, in <module>
    from visualqc import t1_mri
  File "/axiom2/projects/software/arch/linux-xenial-xerus/visualqc/0.3/lib/python3.6/site-packages/visualqc-0.3+68.gb01c5de.dirty-py3.6.egg/visualqc/t1_mri.py", line 17, in <module>
    from mrivis.base import Collage
ModuleNotFoundError: No module named 'mrivis.base'
```

Checking mrivis location:

```
In [1]: import mrivis
/axiom2/projects/software/arch/linux-xenial-xerus/python-modules/20180122/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

In [2]: mrivis.__file__
Out[2]: '/axiom2/projects/software/arch/linux-xenial-xerus/src/visualqc/.eggs/mrivis-0.2.8-py3.6.egg/mrivis/__init__.py'
```

So it's picking up the version that got installed by visualqc, `mrivis-0.2.8`

## Update

Fixed by installing `mrivis` from github, so it looks like you just need to bump the pypi version to be compatible with `visualqc` HEAD

**Comment by raamana** [comment]
Thanks Chris for the detailed report.. I guess I should sync their releases better - given mrivis will likely be stable from now on, it shouldnt be a problem going forward.

also, how did you install VQC, via pip or clone and local install?

**Comment by raamana** [comment]
very glad to see you try it! :)

**Comment by raamana** [comment]
local setup.py is fine with devs like you, who can figure out whats going on.. but I'd suggest basic users go the pip route.

**Comment by raamana** [comment]
closing this I believe you can run it now, please reopen if not.
