### ISSUE TITLE
Warning Message When Loading VisualQC

### ISSUE THREAD

**Issue by atheyers** [raamana/visualqc#15]
* visualqc version: 0.3.3.3
* Python version: 3.5.2
* Operating System: Ubuntu 16.04 Guest on Windows 7

### Description

VisualQC loads but I get this warning message every time:

Extracting feature type: cortical
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/visualqc/workflows.py", line 345, in extract_features
    self.feature_paths[feat_type] = self.feature_extractor(self, feat_type)
  File "/usr/local/lib/python3.5/dist-packages/visualqc/readers.py", line 166, in gather_freesurfer_data
    [read_aparc_stats_wholebrain(qcw.in_dir, id) for id in qcw.id_list])
  File "/usr/local/lib/python3.5/dist-packages/visualqc/readers.py", line 166, in <listcomp>
    [read_aparc_stats_wholebrain(qcw.in_dir, id) for id in qcw.id_list])
  File "/usr/local/lib/python3.5/dist-packages/visualqc/readers.py", line 75, in read_aparc_stats_wholebrain
    hm_data = read_aparc_stats_in_hemi(stats_path, subset)
  File "/usr/local/lib/python3.5/dist-packages/visualqc/readers.py", line 121, in read_aparc_stats_in_hemi
    roi_stats_values[idx, :] = [stat[feat] for feat in subset]
TypeError: 'NoneType' object is not iterable
Unable to extract cortical features - skipping them.
Extracting feature type: subcortical
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/visualqc/workflows.py", line 345, in extract_features
    self.feature_paths[feat_type] = self.feature_extractor(self, feat_type)
  File "/usr/local/lib/python3.5/dist-packages/visualqc/readers.py", line 168, in gather_freesurfer_data
    features = np.vstack([read_aseg_stats(qcw.fs_dir, id) for id in qcw.id_list])
  File "/usr/local/lib/python3.5/dist-packages/visualqc/readers.py", line 168, in <listcomp>
    features = np.vstack([read_aseg_stats(qcw.fs_dir, id) for id in qcw.id_list])
AttributeError: 'FreesurferRatingWorkflow' object has no attribute 'fs_dir'
Unable to extract subcortical features - skipping them.
Features required for outlier detection are not available - skipping it.

**Comment by tjiagoM** [comment]
I confirm I have the same issue.
