### ISSUE TITLE
(IndexError) Cannot execute visualqc_freesurfer in newer versions

### ISSUE THREAD

**Issue by tjiagoM** [raamana/visualqc#23]
* visualqc version: 0.3.5 (installed through pip)
* Python version: 3.7
* Operating System: Linux

### Description

I just tried to run a normal `visualqc_freesurfer` command, but without success as the output in the following section shows. This happened when I tried to use a new environment with recent python and visualqc versions

I don't have any problem in the same folder in a previous version that I had configured (python 3.5 and 
visualqc 0.3.3.3).

### What I Did

```
(env-new) user@server$ visualqc_freesurfer --fs_dir .
/home/user/miniconda/envs/env-new/lib/python3.7/site-packages/visualqc/utils.py:610: UserWarning: The following subjects do NOT have all the required files or some are empty - skipping them!
  'The following subjects do NOT have all the required files or some are empty - skipping them!')
1611420080917


The following files do not exist or empty: 
 /folder_server/1611420080917/mri/aparc+aseg.mgz 


14 subjects are usable for review.
Input folder: .
Output folder: ./visualqc
Preprocessing data - please wait .. 
        (or contemplate the vastness of universe! )
Extracting feature type: cortical
Extracting feature type: subcortical
Traceback (most recent call last):
  File "/home/user/miniconda/envs/env-new/lib/python3.7/site-packages/visualqc/workflows.py", line 346, in extract_features
    self.feature_paths[feat_type] = self.feature_extractor(self, feat_type)
  File "/home/user/miniconda/envs/env-new/lib/python3.7/site-packages/visualqc/readers.py", line 169, in gather_freesurfer_data
    features = np.vstack([read_aseg_stats(qcw.fs_dir, id) for id in qcw.id_list])
  File "/home/user/miniconda/envs/env-new/lib/python3.7/site-packages/visualqc/readers.py", line 169, in <listcomp>
    features = np.vstack([read_aseg_stats(qcw.fs_dir, id) for id in qcw.id_list])
AttributeError: 'FreesurferRatingWorkflow' object has no attribute 'fs_dir'
Unable to extract subcortical features - skipping them.
Traceback (most recent call last):
  File "/home/user/miniconda/envs/env-new/bin/visualqc_freesurfer", line 11, in <module>
    sys.exit(main())
  File "/home/user/miniconda/envs/env-new/lib/python3.7/site-packages/visualqc/__freesurfer__.py", line 11, in main
    freesurfer.cli_run()
  File "/home/user/miniconda/envs/env-new/lib/python3.7/site-packages/visualqc/freesurfer.py", line 1066, in cli_run
    wf.run()
  File "/home/user/miniconda/envs/env-new/lib/python3.7/site-packages/visualqc/workflows.py", line 68, in run
    self.preprocess()
  File "/home/user/miniconda/envs/env-new/lib/python3.7/site-packages/visualqc/freesurfer.py", line 318, in preprocess
    self.detect_outliers()
  File "/home/user/miniconda/envs/env-new/lib/python3.7/site-packages/visualqc/workflows.py", line 371, in detect_outliers
    features = gather_data(self.feature_paths[feature_type], self.id_list)
  File "/home/user/miniconda/envs/env-new/lib/python3.7/site-packages/visualqc/readers.py", line 225, in gather_data
    features = np.vstack([np.genfromtxt(path_list[sid]) for sid in id_list])
  File "/home/user/miniconda/envs/env-new/lib/python3.7/site-packages/visualqc/readers.py", line 225, in <listcomp>
    features = np.vstack([np.genfromtxt(path_list[sid]) for sid in id_list])
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

```

**Comment by raamana** [comment]
That's a cryptic error. could show me the contents of the visualqc folder created, and anything else?

Also, can you try this command with the new option `-old` and let me know if it would work:
```bash
visualqc_freesurfer --fs_dir . -old
```

**Comment by raamana** [comment]
Hi, Did it work?

**Comment by xgrg** [comment]
Worked for me (and I had the same problem).

```
[python3] grg@fusiform:~/git $ visualqc_freesurfer --fs_dir /tmp/test_FS -o /tmp/visualqc                        
11 subjects are usable for review.
Input folder: /tmp/test_FS
Output folder: /tmp/visualqc
Preprocessing data - please wait .. 
        (or contemplate the vastness of universe! )
Extracting feature type: cortical
Extracting feature type: subcortical
Traceback (most recent call last):
  File "/tmp/python3/lib/python3.5/site-packages/visualqc/workflows.py", line 346, in extract_features
    self.feature_paths[feat_type] = self.feature_extractor(self, feat_type)
  File "/tmp/python3/lib/python3.5/site-packages/visualqc/readers.py", line 169, in gather_freesurfer_data
    features = np.vstack([read_aseg_stats(qcw.fs_dir, id) for id in qcw.id_list])
  File "/tmp/python3/lib/python3.5/site-packages/visualqc/readers.py", line 169, in <listcomp>
    features = np.vstack([read_aseg_stats(qcw.fs_dir, id) for id in qcw.id_list])
AttributeError: 'FreesurferRatingWorkflow' object has no attribute 'fs_dir'
Unable to extract subcortical features - skipping them.
Traceback (most recent call last):
  File "/tmp/python3/bin/visualqc_freesurfer", line 11, in <module>
    sys.exit(main())
  File "/tmp/python3/lib/python3.5/site-packages/visualqc/__freesurfer__.py", line 11, in main
    freesurfer.cli_run()
  File "/tmp/python3/lib/python3.5/site-packages/visualqc/freesurfer.py", line 1066, in cli_run
    wf.run()
  File "/tmp/python3/lib/python3.5/site-packages/visualqc/workflows.py", line 68, in run
    self.preprocess()
  File "/tmp/python3/lib/python3.5/site-packages/visualqc/freesurfer.py", line 318, in preprocess
    self.detect_outliers()
  File "/tmp/python3/lib/python3.5/site-packages/visualqc/workflows.py", line 371, in detect_outliers
    features = gather_data(self.feature_paths[feature_type], self.id_list)
  File "/tmp/python3/lib/python3.5/site-packages/visualqc/readers.py", line 225, in gather_data
    features = np.vstack([np.genfromtxt(path_list[sid]) for sid in id_list])
  File "/tmp/python3/lib/python3.5/site-packages/visualqc/readers.py", line 225, in <listcomp>
    features = np.vstack([np.genfromtxt(path_list[sid]) for sid in id_list])
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

[python3] grg@fusiform:~/git $ visualqc_freesurfer --fs_dir /tmp/test_FS -o /tmp/visualqc -old
11 subjects are usable for review.
Input folder: /tmp/test_FS
Output folder: /tmp/visualqc
outlier detection: disabled, as requested.
Attempting to generate the surface visualizations of parcellation ...
Processing 10025
Processing 10016
Processing 10023
Processing 10013
Processing 10019
Processing 10028
Processing 10024
Processing 10026
Processing 10029
Processing 10015
Processing 10010
Restoring ratings from previous session(s), if they exist ..
To be reviewed : 11
```

Thanks @raamana!

**Comment by raamana** [comment]
You're welcome - great to hear that, thanks.

I'll fix this bug soon as soon as I'm done with another deadline.

**Comment by tjiagoM** [comment]
Sorry for the delay. I also confirm that your solution (`visualqc_freesurfer --fs_dir . -old`) worked for me. Although I got another error in the meantime and I will create a separate issue for that.

**Comment by Leema-Krishna-Murali** [comment]
Hi @raamana,

I would like to test the outlier detection module in VisualQC (latest version) and I see the same error as above. Please can assist in how to resolve this error:

$ visualqc_freesurfer --fs_dir '/mnt/fsx/Screening_3DT1w_FSResults' -i '/home/ubuntu/Desktop/visualqc_sub_list.txt' -olt subcortical

visualqc version 0.5.1+25.g1d9d10c for Freesurfer QC
	Time stamp : 2022-03-02 20:18:52

10 subjects are usable for review.
Input folder: /mnt/fsx/fsx/nbg/e2609/g000_301_Screening_3DT1w_Recommend_FSResults_NEW
Output folder: /mnt/fsx/fsx/nbg/e2609/g000_301_Screening_3DT1w_Recommend_FSResults_NEW/visualqc
Preprocessing data - please wait .. 
	(or contemplate the vastness of universe! )
Extracting feature type: subcortical
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/visualqc-0.5.1+25.g1d9d10c-py3.8.egg/visualqc/workflows.py", line 368, in extract_features
    self.feature_paths[feat_type] = self.feature_extractor(self, feat_type)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/visualqc-0.5.1+25.g1d9d10c-py3.8.egg/visualqc/readers.py", line 176, in gather_freesurfer_data
    features = np.vstack([read_aseg_stats(qcw.fs_dir, id) for id in qcw.id_list])
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/visualqc-0.5.1+25.g1d9d10c-py3.8.egg/visualqc/readers.py", line 176, in <listcomp>
    features = np.vstack([read_aseg_stats(qcw.fs_dir, id) for id in qcw.id_list])
**AttributeError: 'FreesurferRatingWorkflow' object has no attribute 'fs_dir'
Unable to extract subcortical features! skipping..
Features required for outlier detection are not available - skipping it.**
Attempting to generate the surface visualizations of parcellation ...

Thank you,
Leema
