### ISSUE TITLE
Type Error: an integer is required (got type bytes) when just test on visualqc_freesurfer -h

### ISSUE THREAD

**Issue by XinQi7788** [raamana/visualqc#44]
* visualqc version: 0.5
* Python version: 3.8.5
* Operating System: Linux 5.4.0-1039-aws

### Description and What I did
I installed VisualQC on my AWS EC2. 

When I tried to test it in terminal by using command line: **visualqc_freesurfer -h**,  got error saying **Type Error: an integer is required (got type bytes)**

### Below is the detailed error information.
/home/Xin/miniconda3/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/home/Xin/miniconda3/bin/visualqc_freesurfer", line 33, in <module>
    sys.exit(load_entry_point('visualqc==0.5+1.g8e386c1', 'console_scripts', 'visualqc_freesurfer')())
  File "/home/Xin/miniconda3/bin/visualqc_freesurfer", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/Xin/miniconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/Xin/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/Xin/miniconda3/lib/python3.8/site-packages/visualqc/__init__.py", line 16, in <module>
    from visualqc.outliers import outlier_advisory
  File "/home/Xin/miniconda3/lib/python3.8/site-packages/visualqc/outliers.py", line 14, in <module>
    from sklearn.ensemble import IsolationForest
  File "/home/Xin/miniconda3/lib/python3.8/site-packages/sklearn/__init__.py", line 64, in <module>
    from .base import clone
  File "/home/Xin/miniconda3/lib/python3.8/site-packages/sklearn/base.py", line 13, in <module>
    from .utils.fixes import signature
  File "/home/Xin/miniconda3/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 13, in <module>
    from .validation import (as_float_array,
  File "/home/Xin/miniconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 27, in <module>
    from ..utils._joblib import Memory
  File "/home/Xin/miniconda3/lib/python3.8/site-packages/sklearn/utils/_joblib.py", line 18, in <module>
    from ..externals.joblib import __all__   # noqa
  File "/home/Xin/miniconda3/lib/python3.8/site-packages/sklearn/externals/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/home/Xin/miniconda3/lib/python3.8/site-packages/sklearn/externals/joblib/parallel.py", line 32, in <module>
    from .externals.cloudpickle import dumps, loads
  File "/home/Xin/miniconda3/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/__init__.py", line 3, in <module>
    from .cloudpickle import *
  File "/home/Xin/miniconda3/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py", line 151, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/home/Xin/miniconda3/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py", line 132, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)

**Comment by raamana** [comment]
Hi @XinQi7788! thank you for reporting this issue. It appears to be something to do with importing of an scikit-learn model and its potential interaction with python 3.8. Are you able to use python 3.6 - if so, can you try run it under python 3.6? 

Can you try add the `-old` flag while trying e.g. `visualqc_freesurfer -old -h` ?

**Comment by XinQi7788** [comment]
Hi Raamana: The issue is resolved after using python 3.6!!! Thank you so much for a quick reply!

**Comment by raamana** [comment]
Very glad to hear that. Please feel free to let me know if you have any feedback or feature requests.

Let me look into what is it about python 3.8 that's the issue?

**Comment by XinQi7788** [comment]
I created a conda environment with python=3.6 for VisualQC, then install it using setup.py code. Now it seems work fine on AWS EC2 except it is slow maybe due to internet speed. 

Actually, without adding _-old_ flag, it works fine as well. 

Thank you very much for so quick reply!

**Comment by raamana** [comment]
You're welcome. Thanks Xin for the notes - I am curious how well the GUI based apps run in AWS EC2? Probably not very different from local desktop except for slow startup etc? 

Let me if your specific application requires any further customization or additional features.

**Comment by XinQi7788** [comment]
It is no difference from local laptop or AWS EC2. But the EC2 is very slow to run visualqc to view the images one-by-one. 

Thank you very much for your reply and we would like to let you know any additional features as needed!
